### ISSUE TITLE
binary release

### ISSUE THREAD

**Issue by efa** [unixwork/xnedit#100] opened 2023-04-25 18:04 UTC
here attached binaries for 2 common SBCs:
1)
Raspberry Pi 3B+, Debian11-32bit, gcc10.2.1, ARMv7l
Raspberry Pi 3B+, Debian11-64bit, gcc10.2.1, aarch64
2) StarFive VisionFive2, DebianSid-64bit, gcc12.2.0, RISCV64

Are generated from current git sources.

Note: the archive are .tgz inside .zip as seems github say support .tgz but refuse to upload them, but work for .zip

[XNEdit1.4.1_Debian11-32bit_gcc10.2.1_ARMv7l.zip](https://github.com/unixwork/xnedit/files/11325516/XNEdit1.4.1_Debian11-32bit_gcc10.2.1_ARMv7l.zip)
[XNEdit1.4.1_Debian11-64bit_gcc10.2.1_aarch64.zip](https://github.com/unixwork/xnedit/files/11425137/XNEdit1.4.1_Debian11-64bit_gcc10.2.1_aarch64.zip)
[XNEdit1.4.1_DebianSid-64bit_gcc12.2.0_RISCV64.zip](https://github.com/unixwork/xnedit/files/11325518/XNEdit1.4.1_DebianSid-64bit_gcc12.2.0_RISCV64.zip)

**Comment by efa** [comment] 2023-04-28 21:37
note: in the "BUILDING XNEDIT" section of Readme, you should it is sayd to install 'libpcre', but I think user need more details, as on Debian I have:

libpcre3-dev
Old Perl 5 Compatible Regular Expression Library - development files
2:8.39-13

libpcre2-dev
New Perl Compatible Regular Expression Library - development files
10.36-2+deb11u1

**Comment by unixwork** [comment] 2023-04-29 17:12
Some distributions call the old lib just libpcre and the new one libpcre2. I decided to use the old lib because some older distributions don't have libpcre2.

My plan is to switch to libpcre2 but also to offer an option to use the old lib.

Even better would be to remove the dependency completely. The library is used by some editorconfig code for wildcard expressions. These wildcard expressions could be re-implemented without regular expressions, the problem is, that there is no good specification for these wildcard expressions, therefore I was forced to use their code.

**Comment by efa** [comment] 2023-05-01 20:12
The v10 finally is Posix compatible, but I understand is not always present

As now, you can simply change the line from:
libpcre
to:
libpcre Perl 5 lib v8.38 (or v8.x)
so users of distributions with both versions, understand which one is the requisite.

**Comment by efa** [comment] 2023-05-09 20:13
added the binary for Raspberry Pi 3B+ @64bit

**Comment by unixwork** [comment] 2023-05-13 15:39
The readme now specifies the libpcre version.

Because I would like to close this issue, can you post the binaries to the Discussions page, maybe #77 or a new thread?

**Comment by efa** [comment] 2023-05-14 08:36
done, see https://github.com/unixwork/xnedit/discussions/101

**Closed** 2023-05-14 09:04 UTC
