### ISSUE TITLE
Problem compiling Xnedit 1.2.0 for Mac OS 10.13.6

### ISSUE THREAD

**Issue by wilsonmaw** [unixwork/xnedit#20] opened 2020-03-24 07:48 UTC
I have been trying to compile xnedit for a 64-bit Mac running 10.13.6.  I am using Makefile.macosx can provide my version if helpful. While I believe that I have tracked down all the needed libraries and correctly point to them in the edited Makefile.macosx, compilation fails with the following message:

Undefined symbols for architecture x86_64:
  "_iconv", referenced from:
      _doOpen in file.o
      _doSave in file.o
      _ConvertEncoding in libNUtil.a(misc.o)
  "_iconv_close", referenced from:
      _doOpen in file.o
      _doSave in file.o
      _ConvertEncoding in libNUtil.a(misc.o)
  "_iconv_open", referenced from:
      _doOpen in file.o
      _doSave in file.o
      _ConvertEncoding in libNUtil.a(misc.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [xnedit] Error 1
make: *** [macosx] Error 2

I am new to this, so please forgive me if this is a simple question, if more information is needed,  or if this is not the appropriate place to ask it. Any help would be greatly appreciated.

**Comment by pucicu** [comment] 2020-03-24 08:16
I can successfully compile xnedit. But I also modified the makefile. See attached. I'm also using macports, therefore, the libs are in /opt/local/…
[Makefile.macosx.zip](https://github.com/unixwork/xnedit/files/4373973/Makefile.macosx.zip)

**Comment by wilsonmaw** [comment] 2020-03-24 08:30
Thank you very much.  I tried this makefile with my library paths but had the same problem. I will use macports to try to address what appears to be a library issue on my end.

**Comment by pucicu** [comment] 2020-03-24 08:48
Perhaps you need to modify the makefile to point to correct location where your Xlibs and mofit-libs are located. In my case, they are in /opt/local/lib because I have installed them using macports. Using homebrew or another way to install the libs, the location is probably different.

**Comment by wilsonmaw** [comment] 2020-03-24 18:03
Thanks again.  I have used port to tidy up libraries and I can compile now.  However, I get this error upon launch of xnedit:
Error: Shell widget nedit has zero width and/or height
make: *** [macosx] Error 1

Frustratingly, this recently happened to my previously functional nedit-5.5, which was the reason that I was trying to install xnedit.  Any thoughts?

**Comment by unixwork** [comment] 2020-03-24 18:19
Hi,

I have seen this error message before on FreeBSD. The solution was to change the link order of Motif and X11 related libs. Try to replace the LIBS line in your Makefile with

LIBS= -L/opt/local/lib/ -lXm -lXt -lX11 -lXmu -lXrender -lXft -lfontconfig  -lm -lXpm  -ljpeg -lpng -liconv

If this doesn't work I can try to create statically linked XNEdit binaries.

**Comment by wilsonmaw** [comment] 2020-03-25 02:11
Thanks again.  I have made these changes to the makefile but still get the "Shell widget nedit has zero width and/or height" error.  I suspect that this may have something to do with the DISPLAY environmental variable being set by XQuartz, as it also happens with Nedit5.5, which I downloaded some time ago as a recompiled binary.  I tried altering the X11 display to check this with no success however.  In any event, if static binaries are available, that would be terrific.  I appreciate all of the the rapid and helpful support provided.

**Comment by dpeterc** [comment] 2020-05-03 13:35
There are two problems here, mainly caused by Apple's departure from Gnu tools and traditional Unix. This makes porting for simple Unix programs difficult. You have several copies of same incompatible libraries installed on the system, and it is hard to know what you actually link at compile time, and what is used at run time.
One is related to iconv library (library that handles conversions between text encodings). Apple ships its own, incompatible with the one from GNU, which is included in homebrew, fink, macports or whatever you are using to port the software to Mac OS X. So you must be sure to link libiconv.2.dylib which comes from your Unix compatibility package manager, not the one included in X OS.
The story with "Shell widget nedit has zero width and/or height" is even more complicated. It is caused by Motif version, which is incompatible with XQuartz. A couple of years ago XQuartz introduced  flat namespace policy in XQaurtz's version of Xt, which caused Motif programs to start failing. The developer provided alternative version of Xt library, so that Motif programs could still work.
http://bugs.motifzone.com/long_list.cgi?buglist=1655
So if you have old Motif, which links to wrong Xt library, you will get this kind of error.
Motif was eventually corrected so that it also works with Apple's way of linking (flat namespace).
http://bugs.motifzone.com/long_list.cgi?buglist=1655
If you compile the latest version of Motif from source, this bug fix is included, and you will no longer see the "Shell widget nedit has zero width and/or height" error.
https://sourceforge.net/p/motif/code/ci/master/tree/

But we still face other problems, which would be trivial on Linux, but on Mac they are a major pain.
You run a program on Linux, and you want to know which libraries is it linking (exact names, versions, with locations). You simply type
ldd nedit
and you get the the full list. Of course, there is no "ldd" on OS X. But there is "otool". So you type
otool -l nedit
and you think you will get the exact list of linked libraries. NOT. It gives you list of libraries and their positions, as they are defined in the nedit binary, not the ones which are actually used.
In order to get the list of libraries which are actually linked, you should use this command:
DYLD_PRINT_LIBRARIES=1 ./xnedit
So now we have a way to know what the program is linking to, and what linker is actually using. This gives you enough information to fix your compile and link command.
But if you want to distribute your binary program, it is not enough, since the development libraries will be missing, or will be in a different place. 
The library paths are hard-coded in the binary.
For example, if you wanted to put Motif library on same directory as the application which it is using it, you would have to use the command:
/usr/bin/install_name_tool -change "/usr/X11R6/lib/libXm.4.dylib" "./libXm.4.dylib" nedit
The first library name is the one reported by "otool -l" and the second one is the library install location. You have to do this for all the libraries, which are not part of standard OS X. And you do it also for all the libraries you modify in this way, and for all the libraries those libraries link to.
Welcome to DLL hell, this time not caused by Microsoft.

I am sorry I can't give you straight simple answer with the fix, since it depends on the additional development system you are using and its location, fink, macbrew, macports, ...

**Comment by wilsonmaw** [comment] 2020-05-03 13:48
Thank you very much for the thoughtful and quite informative response. I figured that this was due to Apple's consistently problematic way of handling libraries, and you've given me many leads to chase down here.  Again, thank you for the help and I'll see if I can make this work.  It's yet another push to just move to Linux.

**Closed** 2020-05-03 13:48 UTC
